# config file for building the CasADi docs (html & PDF user guide)

release: 3.3.0
project: 'CasADi'
copyright: '2018, Joel Andersson, Joris Gillis, Greg Horn'
author: 'Joel Andersson, Joris Gillis, Greg Horn'
links:
  pdf:
    title: PDF version
    href: http://casadi.sourceforge.net/v3.3.0/users_guide/casadi-users_guide.pdf
  cpp_api:
    title: C++ API
    href: http://casadi.sourceforge.net/v3.3.0/api/html/
  python_api:
    title: Python API
    href: ../../python-api
  example_pack:
    title: Example pack
    href: https://github.com/casadi/casadi/releases/download/3.3.0/casadi-example_pack-v3.3.0.zip
